import {
  COLLECTION_TINT_ALPHA,
  collectionPalette,
  fontFaces,
  fontFamily,
  nativeFontName,
  palette,
  radius,
  shadow,
  size,
  space,
  textStyles,
} from './theme.ts';

/** Where `global.css` finds the bundled fonts, relative to the stylesheet. */
const FONT_DIR = '../../../../assets/fonts';

/** `surfaceElevated` -> `surface-elevated`. */
function kebab(name: string): string {
  return name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

/** `#9AA5F2` at 16% -> `rgba(154, 165, 242, 0.16)`. */
function withAlpha(hex: string, alpha: number): string {
  const [r, g, b] = [1, 3, 5].map((start) => parseInt(hex.slice(start, start + 2), 16));
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

/**
 * The global stylesheet, as text: the faces, every token on `:root`, a class per collection that
 * sets its accent for everything inside it, the type scale, and the page ground.
 *
 * Generated from `theme.ts` and committed as `global.css`, which is what Metro compiles. Run
 * `npm run theme` after changing the theme; `theme.test.ts` fails when the two disagree.
 */
export function buildGlobalCss(): string {
  const out: string[] = [];
  const block = (selector: string, declarations: readonly string[]): void => {
    out.push(`${selector} {`, ...declarations.map((line) => `  ${line}`), '}', '');
  };

  out.push(
    '/*',
    ' * GENERATED by `npm run theme` from theme.ts. Do not edit: change theme.ts and regenerate.',
    ' * theme.test.ts fails when this file is out of date.',
    ' */',
    '',
  );

  for (const face of fontFaces) {
    block('@font-face', [
      `font-family: '${face.family}';`,
      `src: url('${FONT_DIR}/${face.file}');`,
      `font-weight: ${face.weight};`,
      ...('italic' in face ? ['font-style: italic;'] : []),
    ]);
  }

  block(':root', [
    ...Object.entries(palette).map(([key, value]) => `--color-${kebab(key)}: ${value};`),
    ...Object.entries(space).map(([key, value]) => `--space-${key}: ${value}px;`),
    ...Object.entries(radius).map(([key, value]) => `--radius-${key}: ${value}px;`),
    ...Object.entries(size).map(([key, value]) => `--size-${key}: ${value}px;`),
    ...Object.entries(shadow).map(([key, value]) => `--shadow-${key}: ${value};`),
  ]);

  // Set on a card, a page or an empty state, these reach everything inside it.
  for (const [id, colors] of Object.entries(collectionPalette)) {
    const surface = 'surface' in colors ? colors.surface : 'var(--color-surface)';
    block(`.collection-${id}`, [
      `--collection-accent: ${colors.accent};`,
      `--collection-tint: ${withAlpha(colors.accent, COLLECTION_TINT_ALPHA)};`,
      `--collection-surface: ${surface};`,
    ]);
  }

  for (const [name, style] of Object.entries(textStyles)) {
    block(`.text-${name}`, [
      `color: var(--color-${kebab(style.color)});`,
      // Native finds a face by its registered name and does no weight matching, so the weight (and
      // the italic) is part of the family name, and `font-weight` is not written.
      `font-family: '${nativeFontName(fontFamily[style.font], style.weight)}';`,
      `font-size: ${style.size}px;`,
      `line-height: ${style.lineHeight}px;`,
      ...('letterSpacing' in style ? [`letter-spacing: ${style.letterSpacing}px;`] : []),
    ]);
  }

  // After the type scale, so a modifier wins a tie with it. Only the ones the screens use.
  block('.text-tertiary', ['color: var(--color-text-tertiary);']);
  block('.text-secondary', ['color: var(--color-text-secondary);']);
  block('.text-collection', ['color: var(--collection-accent, var(--color-text-secondary));']);
  block('.text-accent', ['color: var(--color-accent);']);

  // The host of a routed page is its native screen, which paints nothing by itself.
  block('.screen', ['flex: 1;', 'background-color: var(--color-background);']);

  return out.join('\n').trimEnd() + '\n';
}
